services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5000:80
    depends_on:
    - php
    - mysql
    - mongodb
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/html
    ports:
      - 5173:5173
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
    ports:
      - 5001:80
volumes:
  mysqldata:
  mongodata: